# Creating Pr with following name convention. Common types include feat (a new feature), fix (a bug fix), docs (documentation changes),
# style (formatting, missing semi colons, etc.), refactor (code refactoring), test (adding missing tests), 
# chore (changes to the build process or auxiliary tools and libraries such as documentation generation)
# e.g: feat(ci): Add auto generate changelog workflow
name: Changelog Update

on:
  pull_request:
    branches:
      - main
    types: [closed]

permissions: write-all

jobs:
  update_changelog:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.merge_commit_sha }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install conventional-changelog-cli
        run: npm install -g conventional-changelog-cli

      - name: Configure Git
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'

      - name: Simulate commit for PR title
        run: |
          echo "${{ github.event.pull_request.title }}" > temp_message.txt
          git commit --allow-empty -F temp_message.txt

      - name: Generate changelog
        run: |
          conventional-changelog -p angular -i CHANGELOG.md -s -r 0

      - name: Show git status and changelog contents
        run: |
          git status
          echo "Changelog contents:"
          cat CHANGELOG.md

      - name: Revert temporary commit
        run: git reset HEAD~

      - name: Commit and push changelog update
        run: |
          git add CHANGELOG.md
          git diff --staged --quiet || git commit -m "Update CHANGELOG.md based on PR #${{ github.event.pull_request.number }} title"
          git push origin HEAD:refs/heads/main
